{
    "name": "SPP Registry: Scanner API",
    "category": "OpenSPP",
    "version": "15.0.1.0.12",
    "sequence": 1,
    "author": "OpenSPP.org",
    "website": "https://github.com/openspp/openspp-registry",
    "license": "LGPL-3",
    "development_status": "Alpha",
    "maintainers": ["jeremi", "gonzalesedwin1123", "emjay0921"],
    "depends": [
        "base",
        "spp_change_request",
        "dms",
    ],
    "data": ["security/scanner_security.xml", "views/user_custom_view.xml"],
    "assets": {},
    "demo": [],
    "images": [],
    "application": True,
    "installable": True,
    "auto_install": False,
}
